########################################
# SQLite3 (gem install sqlite3-ruby)
# defaults: &defaults
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000
#
# development:
#   database: db/development.sqlite3
#   <<: *defaults
#
# test:
#   database: db/test.sqlite3
#   <<: *defaults
#
# production:
#   database: db/production.sqlite3
#   <<: *defaults

########################################
# PostgreSQL (gem install pg)
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: warning
  username: postgres

development:
  database: beachpatrol_development
  <<: *defaults

test:
  database: beachpatrol_test
  <<: *defaults